"""empty message

Revision ID: c76ab847407c
Revises: 
Create Date: 2023-05-15 06:54:28.456193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76ab847407c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('html', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl')
    # ### end Alembic commands ###
