"""empty message

Revision ID: ddaa1e17ccdb
Revises: 
Create Date: 2023-05-14 18:04:39.792764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaa1e17ccdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_hash', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('html', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_crawl_hash'), ['crawl_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_crawl_hash'))

    op.drop_table('crawl')
    # ### end Alembic commands ###
